version: "3.8"
services:
  api:
    build: 
      context: ../../
      dockerfile: deploy/docker-ec2/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
    restart: unless-stopped
