"""
POST /api/v1/audit/run — Multi-agent compliance audit.

Executes the full LangGraph pipeline and streams results back as NDJSON.
Each line in the response is a valid JSON object representing either a
progress event (node completion) or the final verdict.

Stream format:
  Line 1: {"event": "node_complete", "node": "document_agent", "progress": 0.2, ...}
  Line 2: {"event": "node_complete", "node": "image_agent", "progress": 0.4, ...}
  ...
  Line N: {"event": "verdict", "verdict": {...}}

Idempotency:
  Each request carries a ``run_id`` (generated by Django).  Before executing
  the graph the endpoint checks DynamoDB for an existing record:
    - Not found     → proceed; record IN_PROGRESS first
    - IN_PROGRESS   → HTTP 409 Conflict (another Lambda is processing it)
    - COMPLETE      → HTTP 200 with the cached verdict as a single JSON line
    - FAILED        → retry allowed (the previous invocation errored out)

Rate limiting:
  Enforced by slowapi at RATE_LIMIT_AUDIT requests per minute per API key.

The Django client reads the stream line-by-line.  It can show progress in the
UI from the node_complete events, then process the final verdict event.
"""

from collections.abc import AsyncGenerator
from typing import Any

import structlog
from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import JSONResponse, StreamingResponse

from app.agents.graph import audit_graph
from app.agents.state import AuditState
from app.config import get_settings
from app.dependencies import DynamoDBDep, SettingsDep
from app.rate_limiter import limiter  # shared singleton \u2014 avoids circular import
from app.schemas.audit import AuditRequest
from app.services import dynamodb_service
from app.utils.streaming import NodeCompleteEvent, VerdictEvent, serialise_event

router = APIRouter(prefix="/audit", tags=["audit"])
logger = structlog.get_logger(__name__)

# Ordered list of node names — used to calculate progress percentage
_NODE_ORDER = ["document_agent", "image_agent", "rule_agent", "evidence_agent", "verdict_agent"]

# Read rate limit from settings once at module load time.
# Safe for Lambda warm starts: settings are cached via lru_cache.
_AUDIT_RATE_LIMIT = get_settings().rate_limit_audit


async def _stream_audit(
    request: AuditRequest, dynamodb_client: Any, table_name: str
) -> AsyncGenerator[str, None]:
    """
    Async generator yielding NDJSON lines as the LangGraph graph executes.

    Yields one NodeCompleteEvent per agent node, then a final VerdictEvent.
    Handles DynamoDB lifecycle: marks COMPLETE on success, FAILED on error.
    """
    initial_state = AuditState(
        asset_id=request.asset_id,
        run_id=request.run_id,
        asset_spec=request.asset_spec,
        s3_image_keys=request.s3_image_keys,
        auditor_remarks=request.auditor_remarks,
        previous_verdicts=[v.model_dump() for v in (request.previous_verdicts or [])],
        errors=[],
    )

    final_verdict: dict[str, Any] | None = None

    try:
        async for event_data in audit_graph.astream(initial_state, stream_mode="updates"):
            # event_data is a dict: {node_name: partial_state_update}
            for node_name, node_output in event_data.items():
                progress = (
                    (_NODE_ORDER.index(node_name) + 1) / len(_NODE_ORDER)
                    if node_name in _NODE_ORDER
                    else 1.0
                )

                progress_event = NodeCompleteEvent(
                    node=node_name,
                    asset_id=request.asset_id,
                    run_id=request.run_id,
                    progress=round(progress, 2),
                )
                yield serialise_event(progress_event)

                # When the verdict node completes, stream the final verdict
                if node_name == "verdict_agent" and "verdict" in node_output:
                    final_verdict = node_output["verdict"]
                    verdict_event = VerdictEvent(verdict=final_verdict)
                    yield serialise_event(verdict_event)

        # Persist the verdict so future retries return the cached result
        if final_verdict is not None:
            dynamodb_service.complete_audit_run(
                dynamodb_client, table_name, request.run_id, final_verdict
            )

    except Exception as exc:
        logger.error("audit_stream_error", run_id=request.run_id, error=str(exc))
        dynamodb_service.fail_audit_run(dynamodb_client, table_name, request.run_id, str(exc))
        raise


@router.post(
    "/run",
    status_code=status.HTTP_200_OK,
    response_model=None,  # Union[StreamingResponse, JSONResponse] is not a valid Pydantic model
    summary="Run compliance audit",
    description=(
        "Execute the full multi-agent compliance audit pipeline. "
        "Returns a streaming NDJSON response with progress events and the final verdict. "
        "Idempotent: re-submitting the same run_id returns the cached verdict."
    ),
    responses={
        200: {
            "content": {"application/x-ndjson": {}},
            "description": "Stream of NDJSON events ending with the compliance verdict.",
        },
        409: {"description": "Audit run is already in progress for this run_id."},
    },
)
@limiter.limit(_AUDIT_RATE_LIMIT)
async def run_audit(
    request: Request,  # Must be named 'request' for slowapi
    audit_request: AuditRequest,  # Pydantic-validated request body
    dynamodb_client: DynamoDBDep,
    settings: SettingsDep,
) -> StreamingResponse | JSONResponse:
    """Start the multi-agent audit pipeline and stream results, with idempotency."""
    log = logger.bind(asset_id=audit_request.asset_id, run_id=audit_request.run_id)
    log.info("audit_run_requested", images=len(audit_request.s3_image_keys))

    # ── Idempotency check ──────────────────────────────────────────────────────
    existing = dynamodb_service.get_audit_run(
        dynamodb_client, settings.dynamodb_audit_table, audit_request.run_id
    )

    if existing:
        if existing["status"] == dynamodb_service.STATUS_IN_PROGRESS:
            log.warning("audit_run_already_in_progress")
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail={
                    "code": "AUDIT_IN_PROGRESS",
                    "message": (
                        f"Audit run '{audit_request.run_id}' is already in progress. "
                        "Wait for it to complete or use a different run_id."
                    ),
                },
            )

        if existing["status"] == dynamodb_service.STATUS_COMPLETE:
            log.info("audit_run_cache_hit", status="COMPLETE")
            return JSONResponse(
                status_code=status.HTTP_200_OK,
                content={"event": "verdict", "verdict": existing["verdict"], "cached": True},
                headers={
                    "X-Run-Id": audit_request.run_id,
                    "X-Asset-Id": audit_request.asset_id,
                    "X-Cache": "HIT",
                    "Cache-Control": "no-cache",
                },
            )

        # STATUS_FAILED or STATUS_ERASED — allow retry
        log.info("audit_run_retry_allowed", previous_status=existing["status"])

    # ── Mark run as IN_PROGRESS before executing the graph ────────────────────
    try:
        dynamodb_service.put_audit_run(
            dynamodb_client,
            settings.dynamodb_audit_table,
            audit_request.run_id,
            audit_request.asset_id,
        )
    except Exception as exc:
        error_name = type(exc).__name__
        if "ConditionalCheckFailed" in error_name or "ConditionalCheckFailed" in str(exc):
            log.warning("audit_run_race_condition_409")
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail={
                    "code": "AUDIT_IN_PROGRESS",
                    "message": f"Audit run '{audit_request.run_id}' was just started by another request.",
                },
            ) from exc
        raise

    log.info("audit_run_started")
    return StreamingResponse(
        _stream_audit(audit_request, dynamodb_client, settings.dynamodb_audit_table),
        media_type="application/x-ndjson",
        headers={
            "X-Run-Id": audit_request.run_id,
            "X-Asset-Id": audit_request.asset_id,
            "Cache-Control": "no-cache",
        },
    )
