"""
Pydantic schemas for the audit workflow endpoint.

Defines the request and response models for POST /api/v1/audit/run.
"""

import html
from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, Field, StringConstraints, field_validator


class Evidence(BaseModel):
    """One piece of evidence contributing to the audit verdict."""

    source_type: Literal["document", "image", "auditor_remark"]

    # Document evidence fields
    doc_id: str | None = None
    doc_type: str | None = None
    filename: str | None = None
    page: int | None = None
    excerpt: str | None = None

    # Image evidence fields
    s3_key: str | None = None
    image_finding: str | None = None

    # Remark evidence fields
    remark_text: str | None = None

    # Common
    finding: str = Field(..., description="Normalised finding statement")
    relevance_score: float | None = Field(default=None, ge=0.0, le=1.0)


class TriggeredRule(BaseModel):
    """A compliance rule that was identified as violated or at risk."""

    rule_id: str = Field(..., description="Unique rule slug derived from document section/clause")
    rule_description: str = Field(..., description="Full text of the requirement")
    severity: Literal["critical", "major", "minor", "observation"]
    evidence_refs: list[int] = Field(
        default_factory=list,
        description="Indices into the evidence list that support this rule trigger",
    )


class AuditVerdict(BaseModel):
    """The final structured compliance verdict produced by the multi-agent pipeline."""

    asset_id: str
    run_id: str = Field(..., description="Unique ID for this audit run, used for idempotency")
    compliance_status: Literal["COMPLIANT", "NON_COMPLIANT", "NEEDS_REVIEW", "INSUFFICIENT_DATA"]
    confidence: float = Field(..., ge=0.0, le=1.0)
    triggered_rules: list[TriggeredRule]
    evidence: list[Evidence]
    recommendations: list[str]
    verdict_reasoning: str = Field(
        ..., description="Full natural-language explanation of the verdict"
    )
    documents_consulted: list[str] = Field(
        default_factory=list,
        description="doc_ids of all documents that contributed to this verdict",
    )
    generated_at: datetime


class AssetSpec(BaseModel):
    """Structured representation of an asset specification."""

    name: str = Field(..., min_length=1, description="Name of the asset")
    category: str = Field(..., min_length=1, description="Asset category (e.g. pump, generator)")
    manufacturer: str | None = Field(default=None, description="Asset manufacturer")
    model_config = {"extra": "allow"}


class AuditRequest(BaseModel):
    """Request body for POST /api/v1/audit/run."""

    asset_id: str = Field(..., min_length=1)
    run_id: str = Field(..., min_length=1, description="Idempotency key — generated by Django")
    asset_spec: AssetSpec = Field(
        ...,
        description="Asset metadata from Django: name, category, manufacturer, specs, etc.",
    )
    s3_image_keys: list[Annotated[str, StringConstraints(pattern=r'^[a-zA-Z0-9/_\-\.]+$')]] = Field(
        ...,
        min_length=1,
        max_length=20,
        description="S3 keys of audit photos uploaded by the auditor (max 20)",
    )
    auditor_remarks: str | None = Field(
        default=None,
        max_length=5000,
        description="Free-text observations from the auditor",
    )
    previous_verdicts: list[AuditVerdict] | None = Field(
        default=None,
        description="Last N audit verdicts for this asset, for trend-aware reasoning",
    )

    @field_validator("auditor_remarks", mode="before")
    @classmethod
    def escape_remarks(cls, v: str | None) -> str | None:
        """SEC-2: HTML-escape remarks to prevent prompt injection."""
        if v is not None:
            return html.escape(v)
        return v
